spring.application.name=taskmanager

# Default to 'dev' profile (H2) for local development
# Railway will automatically use 'prod' if we set the SPRING_PROFILES_ACTIVE variable
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Common Settings
server.port=${PORT:8080}
taskmanager.jwtExpirationMs=86400000
